# -*- coding: utf-8 -*-
"""THERAPY arrangements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a43bU5qzQRo3KK9C-oGvBqTe0ClD9ii9
"""

# Q2(b)

def get_permutations(word):
  if len(word)<=1: return [word]
  else:
    perm_list = []
    for perm in get_permutations(word[1:]):
      for i in range(len(word)):
        perm_list.append(perm[:i] + word[0] + perm[i:])
  return perm_list

def count_arrangements_without_vowels_together(word):
  total_arrangements = get_permutations(word)
  count = 0
  for arrangement in total_arrangements:
    for i in range(len(arrangement)-1):
      if arrangement[i] in 'EA' and arrangement[i+1] in 'EA':
        count += 1
        break
  arrangements_without_vowels_together = len(total_arrangements) - count
  return arrangements_without_vowels_together

word = "THERAPY"
arrangements = count_arrangements_without_vowels_together(word)
print("Number of arrangements of",word,"where the vowels don't come together is,",arrangements)