# -*- coding: utf-8 -*-
"""toffees tiffin box.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UP5WigACqV-p_580ojkMldiVbEWKOZsd
"""

# Q2(a)

import numpy as np

def f(x):
  prob = (x*(x-4)+(x-1)*(x-3))/((2*x-4)*(2*x-5))
  return prob-(67.0/132.0)
def bisection(a,b): # a, b are two guess values
  if(np.sign(f(a))==np.sign(f(b))):
    raise Exception("The scalars a and b do not bound a root")
  m = (a+b)/2
  tol = 1e-5
  if np.abs(f(m))<tol: return m
  elif np.sign(f(a))==np.sign(f(m)): return bisection(m,b)
  elif np.sign(f(b))==np.sign(f(m)): return bisection(a,m)

x_val = int(bisection(4.5,10.0))
print("The value of x is,",x_val) # 4.5, 10.0 are the guess values

print("The total no. of toffees in the first tiffin box is:",(2*x_val-4))