# -*- coding: utf-8 -*-
"""youngest student.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XPQwDqieV5kb5UwKUXqEs7mwcCCtvED
"""

# Q1(b)

from random import randint
A = 5 # no. of students in section A
B = 6 # no. of students in section B
C = 7 # no. of students in section C
total = A+B+C

section = 0
young_std = 0
inf = 100000
for i in range(inf):
  # probability that the student will be from section B
  sec=randint(1,total)
  if (6<=sec<=11):
    section=section+1

  young= randint(1,B)
  if(young==1):
    young_std= young_std+1

prob_secB= float(section)/float(inf)
prob_youngstd= float(young_std)/float(inf)
print("Probability that the chosen student will be the youngest student of the section B is,",round(prob_secB*prob_youngstd,3))