# -*- coding: utf-8 -*-
"""minimum maximum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-77Ze8ste5jifWaaOcvnjKt72kMhmp5
"""

import numpy as np
import matplotlib.pyplot as pl
x = np.linspace(-np.pi/2,9*np.pi/2,23)
y = np.cos(x)

minimax = []
minimay = []
maximax = []
maximay = []
for i in range(len(x)-2):
  slope1 = (y[i+1]-y[i])/(x[i+1]-x[i])
  slope2 = (y[i+2]-y[i+1])/(x[i+2]-x[i+1])

  if(slope1>0 and slope2<0):
    maximax.append(x[i+1])
    maximay.append(y[i+1])
  if(slope1<0 and slope2>0):
    minimax.append(x[i+1])
    minimay.append(y[i+1])

print("Local maxima points:")
for i in range(len(maximax)):
  print("("+str(maximax[i])+","+str(maximay[i])+")")
print("\n")
print("Local minima points:")
for i in range(len(minimax)):
  print("("+str(minimax[i])+","+str(minimay[i])+")")
print("\n")

pl.scatter(x,y,c="k",label="all datapoints")
pl.plot(maximax,maximay,marker="o",c="y",linestyle="None",label="local maxima")
pl.plot(minimax,minimay,marker="o",c="b",linestyle="None",label="local minima")
pl.legend(loc="lower left")
pl.xlabel("$x$")
pl.ylabel("$y$")
pl.show()